### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by johnpaulhayes** [mulesoft-labs/api-console-cli#10]
Hi Folks,

I get the following when I run the following: 

`api-console build ./api.raml`

````/usr/local/lib/node_modules/api-console-cli/bin/api-console-build.js:7
const {ApiBuild} = require('../lib/build');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```
api-console: v0.2.3
Node:  v4.2.6

RAML file was generated and validated using anypoint.mulesoft.com

**Comment by jarrodek** [comment]
What version of Node do you have?

**Comment by jarrodek** [comment]
The module is working on node engine >= 6.4.0 hence the error on lower version.
I will make an appropriate error message on lower versions of node.

**Comment by jarrodek** [comment]
Closed by https://github.com/mulesoft-labs/api-console-cli/commit/8a0b46c0bea54e222a72f52e57485c444c4e2163
