### ISSUE TITLE
AMF API Parser can't work with cd-up "../"

### ISSUE THREAD

**Issue by hubandr** [mulesoft-labs/api-console-cli#35]
When doing "build" with a RAML file or doing "generate-model", the file can't be passed if there is a ../ (cd-up) in the path of -a or <api-file> (generate-model).

This will fail with:

info: AMF ready.
info: Running API parser...
  undefined

Error
    at s9a.d.ZQ (/usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:1677:195)
    at s9a.d.ge (/usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:1687:187)
    at s9a.d.tl (/usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:4188:358)
    at r9a.d.pu (/usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:3539:158)
    at r9a.d.gb (/usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:3539:246)
    at r9a.d.U (/usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:2292:374)
    at ne.d.dwa (/usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:4083:212)
    at /usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:1013:267
    at u.U (/usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:2281:216)
    at /usr/lib/node_modules/api-console-cli/node_modules/amf-client-js/amf.js:2258:317

**Comment by jarrodek** [comment]
This is now fixed in 2.0.1.

It works with a command like:

```sh
api-console build -t "RAML 1.0" ../arc/drive-raml-api-v2/api.raml
```
