### ISSUE TITLE
Exception when trying to generate json

### ISSUE THREAD

**Issue by amitav13** [mulesoft-labs/api-console-cli#7]
Hi,
I have this popping up with both v0.2.2 and v0.2.3: 

`TypeError: datatype_expansion.canonical_form.Exception is not a constructor
    at /usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:582:8
    at cljs.core.MultiFn.G__10851__3 (/usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/cljs/core.cljs:9888:8)
    at cljs.core.MultiFn.G__10851 [as call] (/usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/cljs/core.js:33628:20)
    at /usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:530:138
    at /usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/cljs/core.cljs:4638:38
    at /usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/cljs/core.cljs:2233:21
    at Function.cljs.core.seq_reduce.cljs$core$IFn$_invoke$arity$3 (/usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/cljs/core.js:7640:3)
    at Function.cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 (/usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/cljs/core.cljs:2289:9)
    at Function.cljs.core.mapv.cljs$core$IFn$_invoke$arity$2 (/usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/cljs/core.cljs:4638:10)
    at cljs$core$mapv (/usr/local/lib/node_modules/api-console-cli/node_modules/datatype-expansion/node/cljs/core.cljs:4631:1)`

The command I'm trying to execute is: `api-console generate-json api.raml`

The RAML file in question: [api.raml.zip](https://github.com/mulesoft-labs/api-console-cli/files/1253536/api.raml.zip)

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
This is known bug. @antoniogarrote this is on you ;) Could you please do something about it? I can hide the messages when parsing RAML but then I will never push any change to the expansion library :)

**Comment by jarrodek** [comment]
Fixed by https://github.com/mulesoft-labs/api-console-cli/commit/b96481553599857b6d10369e6c89034915a989c9
